// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

console.log("DATABASE_URL configured:", !!process.env.DATABASE_URL);
console.log(
  "DATABASE_HOST:",
  process.env.DATABASE_URL
    ? new URL(process.env.DATABASE_URL).hostname
    : "missing",
);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
